name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19.0.2+7'
          distribution: 'adopt'

      - name: Build and run backend
        run: |
          mvn clean install

        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
          SPRING_DATASOURCE_USERNAME: myuser
          SPRING_DATASOURCE_PASSWORD: mypassword

      - name: Run backend tests
        run: |
          mvn test

      - name: Install Docker CLI
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Build EurekaServer Docker image
        run: |
          cd EurekaServer/
          docker build -t eureka-server:latest .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push EurekaServer Docker image to Docker Hub
        run: |
          docker tag eureka-server:latest ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:latest

      - name: Build RegistrationService Docker image
        run: |
          cd RegistrationService/
          docker build -t registration-service:latest .
      
      - name: Push RegistrationService Docker image to Docker Hub
        run: |
          docker tag registration-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/registration-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/registration-service:latest

      - name: Build MailingService Docker image
        run: |
          cd MailingService/
          docker build -t mailing-service:latest .
      
      - name: Push MailingService Docker image to Docker Hub
        run: |
          docker tag mailing-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/mailing-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mailing-service:latest

      - name: Build PostService Docker image
        run: |
          cd PostService/
          docker build -t post-service:latest .
      
      - name: Push PostService Docker image to Docker Hub
        run: |
          docker tag post-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/post-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/post-service:latest
      
      - name: Build API-Gateway Docker image
        run: |
          cd API-Gateway/
          docker build -t api-gateway:latest .
      
      - name: Push API-Gateway Docker image to Docker Hub
        run: |
          docker tag api-gateway:latest ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build and run frontend
        run: |
          cd front-end/front-end
          npm install
          ng build --configuration=production

      - name: Build and push frontend Docker image
        run: |
          cd front-end/front-end
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
